# -*- coding: utf-8 -*-
"""Copy of readmodel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_MmqDmgMNjJfaXLAsqU0OBEKxPmwuioA
"""
def predict(input):
    # from google.colab import drive
    # drive.mount('/content/drive')

    import tensorflow as tf
    from tensorflow import keras
    from keras.models import load_model
    from tensorflow.keras.preprocessing.text import Tokenizer
    from tensorflow.keras.preprocessing.sequence import pad_sequences

    model = tf.keras.models.load_model('model.h5')

    tokenizer = Tokenizer()

    maxlen = 500
    # input = ['tokomedia is delighted to offer you the full-time position of software engineer with an anticipated start date of januari 13, contingent upon drug screening']
    input
    import pickle

    # loading
    with open('tokenizer.pickle', 'rb') as handle:
        tokenizer = pickle.load(handle)

    input = tokenizer.texts_to_sequences(input)
    input = pad_sequences(input, maxlen=maxlen)

    output = (model.predict(input) >=0.5).astype(int)

    print(output)

    from json import JSONEncoder
    import numpy

    class NumpyArrayEncoder(JSONEncoder):
        def default(self, obj):
            if isinstance(obj, numpy.ndarray):
                return obj.tolist()
            return JSONEncoder.default(self, obj)

    import json

    last = json.dumps(output, cls=NumpyArrayEncoder)
    if last == "[[1]]":
        last = "Fraud Job"
    elif last == "[[0]]": 
        last = "Real Job"

    jsonoutput = {
        "Prediction" : last
    }

    dump = json.dumps(jsonoutput)

    return dump
